### ISSUE TITLE
Error bringing up environment with vagrant

### ISSUE THREAD

**Issue by sundayoyeniyi** [ForestTechnologiesLtd/devopsplayground2-elk-stack#1]
Hi

Trying to use the README but vagrant won't run to completion successfully.  See screenshot below:

Any advice on this will be appreciated.
![screen shot 2016-03-07 at 10 53 33](https://cloud.githubusercontent.com/assets/3162619/13567803/637fa4b6-e455-11e5-888e-718d7aebaef5.png)

SO.

**Comment by micheldlebeau** [comment]
Hi Sunday, are you behind a proxy by any chance?

**Comment by jvelasquez** [comment]
Hi sundayoyeniyi

In addition of the question above, can you please provide us with the full output?

**Comment by sundayoyeniyi** [comment]
Hi Kourtis, yes, I am behind a proxy.  I do have vagrant-proxyconf plugin installed on the host though.  

Thanks

Sunday

**Comment by sundayoyeniyi** [comment]
@jvelasquez - see full output below:

[output.txt](https://github.com/ForestTechnologiesLtd/devopsplayground2-elk-stack/files/161377/output.txt)

Sunday

**Comment by micheldlebeau** [comment]
Do you have the no_proxy parameter set for the vagrant-proxyconf plugin? 
If not try settting it, if it doesn't work please paste your Vagrantfile here so that we can see what can be wrong.
If it is already set, what is it set to?
Thank you for the output.txt

**Comment by sundayoyeniyi** [comment]
@Kourkis - I've just set the no_proxy parameter and result is same as in previous output.txt

complete Vagrantfile is pasted below:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant file for DevOps Playground #2
# Author: Angus Williams <angus@forest-technologies.co.uk>
# Now modified by SO.

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "http://X.X.X.X:YYYY/"
    config.proxy.https    = "http://X.X.X.X:YYYY/"
    config.proxy.no_proxy = "localhost,127.0.0.1,.example.com"
  end

  # Ubuntu 14.04
  config.vm.box = "ubuntu/trusty64"

  # Foward elastic service ports to localhost
  config.vm.network "forwarded_port", guest: 9200, host: 9200 # elasticsearch
  config.vm.network "forwarded_port", guest: 5601, host: 5601 # kibana4

  config.vm.provider "virtualbox" do |vb|
    # Add another CPU
    vb.cpus = "2"
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    vb.name = "ELK-Stack"
  end

  # Install docker & docker-compose
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
    sudo apt-get update
    sudo apt-get install -y docker-engine python-pip
    sudo usermod -aG docker vagrant
    sudo pip install docker-compose
    cd /vagrant && docker-compose build && docker-compose pull
  SHELL
end 
```

**Comment by micheldlebeau** [comment]
Can you try adding 10.0.0.0/8 to your no_proxy?

**Comment by sundayoyeniyi** [comment]
@Kourkis - tried adding it and error remains the same - failed while pulling in images from https://index.docker.io/......

**Comment by jvelasquez** [comment]
@sundayoyeniyi - can you verify you can do "nslookup index.docker.io" in both your Host and inside the VM (try sshing in the VM using user/pass vagrant/vagrant)

**Comment by sundayoyeniyi** [comment]
@jvelasquez - "nslookup index.docker.io" seems to fail from the host - OS/X:

![screen shot 2016-03-07 at 16 05 50](https://cloud.githubusercontent.com/assets/3162619/13574995/813b6d0e-e47e-11e5-8802-f80fd6d73c78.png)

It seems to be ok from the guest VM:

![screen shot 2016-03-07 at 16 04 20](https://cloud.githubusercontent.com/assets/3162619/13574940/4a78a534-e47e-11e5-923f-5f230d68ebb8.png)

**Comment by jvelasquez** [comment]
Hi @sundayoyeniyi,

When a proxy refuses a connection establishment, normally Vagrant Output should throw something like this: 
`==> default: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease`
1. Can you try add/modify the following line to the VagrantFile (under the proxy section) and give it another try? `config.proxy.no_proxy = ".docker.io,.ubuntu.com,.dockerproject.org,.localhost,127.0.0.1"`
2. Have you tried setting this example up without a proxy?
3. and by the way, do you have the latest code from our repository?

Javi

**Comment by micheldlebeau** [comment]
Issue closed for now, please open it again if needed.
